[telegram]
secret_file = ".telegram_api_token"

[openai]
secret_file = ".openai_key"
model = "text-davinci-003"
temperature = 0.1
max_tokens = 256

[gameworld]
#seed = 348924
template_path = 'templates/02-generate-plot.jinja2'
plot =  """
It's a typical day in the library, with each character carrying out their own business. Sherlock Holmes is investigating a case, Jean-Luc Picard is reading a book, Taylor Swift is writing music, and Nancy Pearl is busy with library work.

Suddenly, Taylor Swift is found dead in one of the aisles of the library. The players must find out who the killer is and what their motives were.

After investigating the scene, it becomes clear that the killer must have been one of the four characters in the library at the time of the murder. The player must use their detective skills to gather clues and interrogate the suspects to find out who committed the crime.

The killer turns out to be Nancy Pearl, the librarian. She had a personal grudge against Taylor Swift, who had been causing trouble in the library and being disrespectful to Nancy. Nancy snapped and killed Taylor in a fit of rage.

It's up to the player to gather the evidence and put the pieces together to figure out who the killer is and bring them to justice.
"""


[[gameworld.characters]]
name =  "Sherlock Holmes"
description =  "The legendary detective created by Sir Arthur Conan Doyle, known for his exceptional intellect, powers of observation, and deductive reasoning."

[[gameworld.characters]]
name =  "Jean-Luc Picard"
description =  "A fictional character and the captain of the USS Enterprise in the Star Trek: The Next Generation television series. He is a cultured, intelligent, and compassionate leader who values diplomacy over violence."

[[gameworld.characters]]
name =  "Taylor Swift"
description =  "A real-life American singer-songwriter known for her pop, country, and pop-rock music, as well as her personal life which is often the subject of media attention."

[[gameworld.characters]]
name =  "Nancy Pearl"
description =  "Librarian"

[[gameworld.characters]]
name =  "Austin Powers"
description =  "A fictional character and the protagonist of the Austin Powers film series. He is a flamboyant, eccentric, and often clueless spy who parodies the spy genre."

[[gameworld.characters]]
name =  "James Bond"
description =  "The suave and debonair spy created by Ian Fleming, who uses his wit, charm, and deadly skills to protect his country and solve crimes."

[[gameworld.characters]]
name =  "Gordon Ramsay"
description =  "A real-life British chef, restaurateur, and television personality, best known for his fiery personality and critical commentary on cooking shows such as Hell's Kitchen and Kitchen Nightmares."

[[gameworld.characters]]
name = "Harry Potter"
description = "The protagonist of J.K. Rowling's Harry Potter series, he is a young wizard who discovers his true heritage and battles the evil Lord Voldemort."

[[gameworld.characters]]
name = "Darth Vader"
description = "a central character in the Star Wars franchise, he is a former Jedi Knight who turns to the dark side and becomes a Sith Lord."

[[gameworld.characters]]
name = "Tony Stark (Iron Man)"
description = "a Marvel Comics character and the alter-ego of genius inventor Tony Stark, he uses his high-tech suit of armor to fight evil and protect the world."

[[gameworld.characters]]
name = "Katniss Everdeen"
description = "the protagonist of the Hunger Games trilogy by Suzanne Collins, she is a strong and resourceful young woman who becomes a symbol of hope and rebellion against the oppressive government."

[[gameworld.characters]]
name = "Elon Musk"
description = "an entrepreneur, inventor, and CEO, known for his innovative and ambitious work in fields such as electric cars, renewable energy, and space travel."

[[gameworld.characters]]
name = "Queen Elizabeth II"
description = "The Queen of the United Kingdom and the Commonwealth Realms, known for her longevity, her dedication to her role and her commitment to public service."

[[gameworld.characters]]
name = "Homelander"
description = "A charismatic but dangerous leader of the Seven in 'The Boys', who uses his powers and influence for his own gain and will stop at nothing to maintain control."

[[gameworld.characters]]
name = "Walter White"
description = "A high school chemistry teacher turned methamphetamine manufacturer in the crime drama 'Breaking Bad'."

[[gameworld.characters]]
name = "Buffy Summers"
description = "A young girl chosen to battle vampires and other supernatural forces in the TV series 'Buffy the Vampire Slayer'."

[[gameworld.characters]]
name = "Neo"
description = "A computer programmer who discovers he is 'The One', a prophesied hero destined to save humanity in the 'Matrix' trilogy."

[[gameworld.locations]]
name = "Library"
description = "A typical library as known like in the 1980s. Three levels, including a basement. Kind of comfy, with a corner with a couch and a few armchairs."

[[gameworld.locations]]
name =  "Orient Express"
description =  "The famous train from Agatha Christie's novel 'Murder on the Orient Express'."

[[gameworld.locations]]
name =  "Elbphilharmony"
description =  "The Elbphilharmonie is a concert hall located on the harbor of Hamburg and is known for its unique architecture and acoustics."

[[gameworld.locations]]
name =  "USS Enterprise"
description =  "The USS Enterprise (NCC-1701) is a starship of the United Federation of Planets in the Star Trek franchise."

[[gameworld.locations]]
name =  "Old Elbe Tunnel"
description =  "A pedestrian and vehicle tunnel in Hamburg, opened in 1911."

[[gameworld.locations]]
name =  "Ohlsdorf Cemetery"
description =  "The biggest rural cemetery in the world. Most of the people buried at the cemetery are civilians, but there is also a large number of victims of war from various nations."

[[gameworld.locations]]
name =  "St. Michael's Church"
description =  "St. Michael's Church is one of Hamburg's five Lutheran main churches and one of the most famous churches in the city. St. Michaelis is a landmark of the city and it is considered to be one of the finest Hanseatic Protestant baroque churches."

[prompts]
user_template_path = 'templates/05-user-input.jinja2'
plot_template_path = 'templates/04-introduction.jinja2'
case_closed_template_path = 'templates/06-case_solved_query.jinja2'
