[openai]
secret_file = ".openai_key"
model = "text-davinci-003"
temperature = 0.7
max_tokens = 2048

[gameworld]
seed = 1337
template_path = 'templates/game_world_builder.jinja2'

[prompts]
user_template_path = 'templates/user_prompt.jinja2'
plot_template_path = 'templates/plot_info.jinja2'
